### ISSUE TITLE
blanket 0.5.0-1~ubuntu20.04.1 - AttributeError: 'Child' object has no attribute 'bind_model'

### ISSUE THREAD

**Issue by tapasbose** [rafaelmardojai/blanket#190] opened 2021-10-01 04:31 UTC
Hello,
I really love this application. Unfortunately, after upgrading to blanket (0.5.0-1~ubuntu20.04.1) apparently, it got broken.

```
$ /usr/bin/python3 /usr/bin/blanket
Traceback (most recent call last):
  File "/usr/share/blanket/blanket/presets.py", line 48, in __init__
    self.presets_list.bind_model(self.model, self._create_widget)
AttributeError: 'Child' object has no attribute 'bind_model'
Traceback (most recent call last):
  File "/usr/share/blanket/blanket/main.py", line 140, in do_activate
    self.window = BlanketWindow(self.mainplayer, application=self)
  File "/usr/share/blanket/blanket/window.py", line 123, in __init__
    self.setup()
  File "/usr/share/blanket/blanket/window.py", line 151, in setup
    self.setup_presets()
  File "/usr/share/blanket/blanket/window.py", line 168, in setup_presets
    self.update_title(self.presets_chooser.selected)
  File "/usr/share/blanket/blanket/window.py", line 254, in update_title
    if preset.id != Settings.get().default_preset:
AttributeError: 'NoneType' object has no attribute 'id'
```

I am in Ubuntu 20.04.3 LTS. Python version: 3.8.10, Python GTK version: 3.24.20.

Thanks in advance.
Regards

**Comment by rafaelmardojai** [comment] 2021-10-01 11:40
Duplicate of #188

**Closed** 2021-10-01 11:41 UTC
