### ISSUE TITLE
Add tray icon to access the app rapidly when closed but running

### ISSUE THREAD

**Issue by Porrumentzio** [rafaelmardojai/blanket#44] opened 2020-09-12 16:07 UTC
Since the sound can still be played when *closed* the app, what I lack is rapid way to access to it (instead of going to the system menu, search for it and opening) to change sound levels.

I think that this would be good solution to this. What do you think?

**Comment by rafaelmardojai** [comment] 2020-09-12 16:13
You should be able to open the app by clicking somewhere in the MPRIS integration.

If you can't, you should report it to your desktop. I don't know how Mate handles this.

**Comment by Porrumentzio** [comment] 2020-09-12 16:23
Is it supposed that with MPRIS integration there should be a tray icon? I don't really now how it works :sweat_smile:

**Comment by rafaelmardojai** [comment] 2020-09-12 16:32
It depends on your desktop.

GNOME for example, integrates MPRIS with a banner in the notification area, here's Blanket and a music player:
![Captura de pantalla de 2020-09-12 11-27-07](https://user-images.githubusercontent.com/6210397/93000019-0d8c1e80-f4eb-11ea-99fe-ec1de2815a10.png)
If you click the banner the app will show up.

I think KDE adds an icon in the panel, and so on.
But I don't know how MATE integrates MPRIS.

**Comment by Porrumentzio** [comment] 2020-09-12 16:41
Understood. So definitively, it's not like that, and the app can't be opened by clicking.

**Comment by rafaelmardojai** [comment] 2020-09-12 17:01
How looks the indicator to you in MATE?

**Comment by Porrumentzio** [comment] 2020-09-12 18:16
I even don't now if there is such thing. The most similar is the sound-control panel.

**Comment by rafaelmardojai** [comment] 2020-09-12 18:45
You don't have media controls in MATE?

**Comment by Porrumentzio** [comment] 2020-09-12 18:47
Seems that not, I didn't find anything like that.

**Comment by rafaelmardojai** [comment] 2020-09-12 18:56
Doesn't MATE has MPRIS controls in the volume indicator?

**Comment by Porrumentzio** [comment] 2020-09-12 18:56
This maybe:
![irudia](https://user-images.githubusercontent.com/61913683/93002897-7d75c580-f53a-11ea-8da3-9960801e928c.png)

**Comment by rafaelmardojai** [comment] 2020-09-12 19:00
Nothing like this in the panels?
![1UZHe](https://user-images.githubusercontent.com/6210397/93002956-3f5bb000-f500-11ea-9cae-752599fa353d.png)

**Comment by Porrumentzio** [comment] 2020-09-12 19:02
Nope. When Audacious playing, right click on its tray icons allows to pause/play and so on; left click opens the app.

**Comment by rafaelmardojai** [comment] 2020-09-12 19:07
> Nope. When Audacious playing, right click on its tray icons allows to pause/play and so on; left click opens the app.

That sounds like Audacious builtin systray. Strange to know that MATE doesn't have MPRIS support.

@apandada1 how does it play in Cinnamon?

**Comment by Porrumentzio** [comment] 2020-09-12 19:12
This is the only what I have found:
[msd-mpris-manager.c](https://github.com/mate-desktop/mate-settings-daemon/blob/master/plugins/mpris/msd-mpris-manager.c)

MATE is a fork of GNOME2

**Comment by rafaelmardojai** [comment] 2020-09-12 19:16
> MATE is a fork of GNOME2

I know, but i thought they were using old Ubuntu's `indicator-sound` or something.

**Comment by apandada1** [comment] 2020-09-13 02:35
> @apandada1 how does it play in Cinnamon?

It plays correctly even after closing the app. It shows up in the volume indicator, and can be controlled with laptop's function keys. And, the app can again be opened quickly, by clicking the :arrow_up: button in the sound applet.

![Screenshot from 2020-09-13 07-56-47](https://user-images.githubusercontent.com/3063132/93008864-6dc1a580-f569-11ea-806c-8425f32998bb.png)

**Comment by rafaelmardojai** [comment] 2020-09-13 12:32
I'm closing this as a wontfix for the systray. I think MPRIS is enough for our needs, and widely supported (GNOME, KDE, Xfce, Cinnamon, etc.).

@Porrumentzio probably you can find some extension/applet for MATE that provides better MPRIS support. But researching looks like MATE already have decent support, so i don't know if is a fact of the Manjaro implementation.

**Closed by rafaelmardojai** 2020-09-13 12:32 UTC

**Comment by haggen88** [comment] 2020-09-21 03:34
@rafaelmardojai  a query. Is there a whiter version of the blanket icon? At the moment in Cinnamon [Mint 20] it looks like this:

![MB](https://user-images.githubusercontent.com/68134588/93731104-f5c73100-fba1-11ea-90c7-206e6f77ee57.png)

**Comment by Porrumentzio** [comment] 2020-09-21 15:04
This is the new one since 2020/09/21
![irudia](https://user-images.githubusercontent.com/61913683/93781849-1a66eb80-fc2a-11ea-9b13-c74d60a714af.png)

**Comment by rafaelmardojai** [comment] 2020-09-21 15:17
> This is the new one since 2020/09/21

Not really, @haggen88 is getting the icon for pulseaudio, which don't have white borders. 

If the icon is `symbolic` the DE should be able to turn it white like GNOME shell.

![Captura de pantalla de 2020-09-21 10-16-24](https://user-images.githubusercontent.com/6210397/93785366-a1e53800-fbf3-11ea-9fa1-c8c52c3c8c6d.png)

![Captura de pantalla de 2020-09-21 10-17-01](https://user-images.githubusercontent.com/6210397/93785359-a0b40b00-fbf3-11ea-9b76-0ac8d6914039.png)

**Comment by ashishbinu** [comment] 2021-05-19 09:34
I don't get systray in kde.Is that bug in the software.I get systray for various other applications like flameshot, ulauncher, mailspring,etc.

![Systray](https://user-images.githubusercontent.com/56691622/118790318-45860580-b8b3-11eb-9c19-921ee4774823.png)

**Comment by apandada1** [comment] 2021-05-19 09:57
@ashishbinu This is KDE issue is probably a duplicate of #96 (Blanket does not register itself as a media playing application in KDE). Do the play/pause buttons work for you?

**Comment by ashishbinu** [comment] 2021-05-19 10:13
> Do the play/pause buttons work for you?

@apandada1  There is no play/pause button in my system if the windows is closed by `ctrl+w`.I can only mute the sound using volume control of blanket in my panel.

But having a systray to open the closed blanket window, having a play/pause button, a quit button would be good feature. Should I open an issue for that?

**Comment by apandada1** [comment] 2021-05-19 11:09
> There is no play/pause button in my system if the windows is closed by ctrl+w.I can only mute the sound using volume control of blanket in my panel.

I was referring to the media control buttons of a laptop. The play/pause button in the CSD headerbar, work perfectly on KDE.
When Blanket is minimized, there will be a way to play/pause once #96 is fixed. Other media players (e.g. VLC, lollypop) can be played and paused within KDE's sound applet. Blanket somehow cannot register itself as a media player in KDE.

**Comment by Porrumentzio** [comment] 2021-05-19 17:31
@ashishbinu, just what you ask for was asked before and rejected, see #44
